export const DO_NOTHING = "DO_NOTHING";

export const UPDATE_CART = "ADD TO BASKET";
export const PUT_CONTENT_IN_FORM_HOLDER = "PUT_CONTENT_IN_FORM_HOLDER";
export const ADD_NEW_SHOP = "ADD_NEW_SHOP";
export const ADD_NEW_PRODUCT = "ADD_NEW_PRODUCT";
export const PREVIOUS_PAGE = -1;
export const SET_ACTIVE_SHOP = "SET_ACTIVE_SHOP";
export const SET_FIREBASE_AUTH = "SET_FIREBASE_AUTH";
export const SET_DONKOMI_AUTH = "SET_DONKOMI_AUTH";
export const SET_MARKET_NEWS = "SET_MARKET_NEWS"; 
export const SET_MARKET_NEWS_DETAILS = "SET_MARKET_NEWS_DETAILS";
export const INSTANTIATE_EXPLORER = "INSTANTIATE_EXPLORER";
export const ITEM_FULL_VIEW = "ITEM_FULL_VIEW";
export const SET_SELLER_ORDERS = "SET_SELLER_ORDERS"; 
export const SET_CLIENT_ORDERS = "SET_CLIENT_ORDERS";
export const SET_CLIENT_COMPLETED_ORDERS = "SET_CLIENT_COMPLETED_ORDERS"; 
export const SET_SELLER_COMPLETED_ORDERS = "SETS_SELLER_COMPLETED_ORDERS";
